Models/Learner.cs
using System.ComponentModel.DataAnnotations;
using UTC_LAB_4.Models;

namespace UTC_LAB_4.Models
{
    public class Learner
    {
        public Learner()
        {
            Enrollments = new HashSet<Enrollment>();
        }

        [Display(Name = "ID")]
        public int LearnerID { get; set; }

        [Display(Name = "Lastname")]
        public string LastName { get; set; }

        [Display(Name = "First mid name")]
        public string FirstMidName { get; set; }

        [Display(Name = "Enrollment date")]
        [DataType(DataType.Date)]
        public DateTime EnrollmentDate { get; set; }

        [Display(Name = "Major ID")]
        public int MajorID { get; set; }
        public virtual Major? Major { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
}

Controllers/LearnerController.cs
using Microsoft.AspNetCore.Mvc;
using UTC_LAB_4.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UTC_LAB_4.Models;
using System.Diagnostics;
using Newtonsoft.Json;
using System.Security.Cryptography;

namespace UTC_LAB_4.Controllers
{
    public class LearnerController : Controller
    {
        private SchoolContext db;
        private int pageSize = 3;

        public LearnerController(SchoolContext context)
        {
            db = context;
        }
        public async Task<IActionResult> Index(int? mid, int pageIndex = 1)
        {
            if (mid == null)
            {
                var learners = await db.Learners.Include(m => m.Major)
                    .Skip((pageIndex - 1) * pageSize)
                    .Take(pageSize)
                    .ToListAsync();

                var count = db.Learners.Count();
                var totalPages = (int)Math.Ceiling(count / (double)pageSize);

                ViewBag.HasPreviousPage = pageSize > 1;
                ViewBag.HasNextPage = pageIndex < totalPages;
                ViewBag.TotalPages = totalPages;
                ViewBag.Count = count;
                ViewBag.PageIndex = pageIndex;

                return View(learners);
            }
            else
            {
                var learners = db.Learners
                    .Skip((pageIndex - 1) * pageSize)
                    .Take(pageSize)
                    .Where(l => l.MajorID == mid)
                     .Include(m => m.Major).ToList();

                var count = db.Learners
                    .Where(l => l.MajorID == mid).Count();
                var totalPages = (int)Math.Ceiling( count / (double)pageSize);


                ViewBag.HasPreviousPage = pageSize > 1;
                ViewBag.HasNextPage = pageIndex < totalPages;
                ViewBag.TotalPages = totalPages;
                ViewBag.Count = count;
                ViewBag.PageIndex = pageIndex;

                return View(learners);
            }
        }

        public IActionResult Page(int pageIndex = 1)
        {
            var learners = db.Learners
                   .Skip((pageIndex - 1) * pageSize)
            .Take(pageSize)
                    .Include(m => m.Major).ToList();

            var count = db.Learners.Count();

            var totalPages = (int)Math.Ceiling(count / (double)pageSize);

            ViewBag.HasPreviousPage = pageSize > 1;
            ViewBag.HasNextPage = pageIndex < totalPages;
            ViewBag.TotalPages = totalPages;
            ViewBag.Count = count;
            ViewBag.PageIndex = pageIndex;

            return PartialView(learners);
        }

        public IActionResult IndexAjax(int? mid)
        {
            if (mid == null)
            {
                try
                {
                    var learners = db.Learners.Include(m => m.Major).ToList();
                    return View(learners);
                }
                catch
                {
                    Response.Redirect("/Notfoundpage");
                    return BadRequest();
                }
            }
            else
            {
                try
                {
                    var learners = db.Learners.Where(l => l.MajorID == mid)
                     .Include(m => m.Major).ToList();
                    return View(learners);
                }
                catch
                {
                    Response.Redirect("/Notfoundpage");
                    return BadRequest();
                }

            }
        }


        public IActionResult LearnByMajorID(int mid)
        {
            var learners = db.Learners
                .Where(l => l.MajorID == mid)
                .Include(m => m.Major).ToList();

            var view = PartialView("LearnerTable", learners);

            return view;
        }

        //thêm 2 action create
        public IActionResult Create()
        {
            //dùng 1 trong 2 cách để tạo SelectList gửi về View qua ViewBag để
            //hiển thị danh sách chuyên ngành (Majors)
            var majors = new List<SelectListItem>(); //cách 1
            foreach (var item in db.Majors)
            {
                majors.Add(new SelectListItem
                {
                    Text = item.MajorName,

                    Value = item.MajorID.ToString()
                });

            }
            ViewBag.MajorID = majors;
            ViewBag.MajorID = new SelectList(db.Majors, "MajorID", "MajorName"); //cách 2
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("FirstMidName,LastName,MajorID,EnrollmentDate")]
            Learner learner)
        {
            if (ModelState.IsValid)
            {
                db.Learners.Add(learner);
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            //lại dùng 1 trong 2 cách tạo SelectList gửi về View để hiển thị danh sách Majors
            ViewBag.MajorID = new SelectList(db.Majors, "MajorID", "MajorName");
            return View();
        }

        [HttpPost]
        public IActionResult Delete(int LearnerID)
        {
            var dbLearner = db.Learners.FirstOrDefault(x => x.LearnerID == LearnerID);

            if (dbLearner != null)
            {
                db.Learners.Remove(dbLearner);
                try
                {
                    db.SaveChanges();

                    return Ok(JsonConvert.SerializeObject(
                        new
                        {
                            status = "success",
                        }
                     ));
                }
                catch (Exception ex)
                {
                    Debug.WriteLine(ex.ToString());
                    return BadRequest(JsonConvert.SerializeObject(
                        new
                        {
                            error = "Can not delete this learner."
                        }
                    ));
                }
            }

            return BadRequest(JsonConvert.SerializeObject(
                new
                {
                    error = "Can not delete this learner."
                }
            ));
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.MajorID = new SelectList(db.Majors, "MajorID", "MajorName");
            var list = db.Learners.ToList();

            foreach (var item in list)
            {
                if (item.LearnerID == id) return View(item);
            }


            return View(new Learner());
        }

        [HttpPost]
        public void Edit([Bind("LearnerID,FirstMidName,LastName,MajorID,EnrollmentDate")]
            Learner learner)
        {
            var dbLearner = db.Learners.FirstOrDefault(x => x.LearnerID == learner.LearnerID);
            if (dbLearner == null) return;

            dbLearner.LearnerID = learner.LearnerID;
            dbLearner.LastName = learner.LastName;
            dbLearner.FirstMidName = learner.FirstMidName;
            dbLearner.MajorID = learner.MajorID;
            dbLearner.EnrollmentDate = learner.EnrollmentDate;

            db.SaveChanges();

            // Redirect to Index
            Response.Redirect("/Learner");
        }

    }
}

ViewComponents/MajorAjaxViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using UTC_LAB_4.Data;
using UTC_LAB_4.Models;

namespace UTC_LAB_4.ViewComponents
{
    public class MajorAjaxViewComponent : ViewComponent
    {
        private SchoolContext db;
        private List<Major> majors = new List<Major>();

        public MajorAjaxViewComponent(SchoolContext _context)
        {
            db = _context;
            majors = db.Majors.ToList();
        }

        public IViewComponentResult Invoke()
        {
            return View("RenderMajorAjax", majors);
        }
    }
}

ViewComponents/MajorViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using UTC_LAB_4.Data;
using UTC_LAB_4.Models;

namespace UTC_LAB_4.ViewComponents
{
    public class MajorViewComponent : ViewComponent
    {
        private SchoolContext db;
        private List<Major> majors = new List<Major>();

        public MajorViewComponent(SchoolContext _context)
        {
            db = _context;
            majors = db.Majors.ToList();
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View("RenderMajor", majors);
        }
    }
}

Views/Learner/Create.cshtml
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Learner
<h1>Create</h1>
<div>
    <div asp-validation-summary="All" class="text-danger"></div>
    <form asp-controller="Learner" asp-action="Create" method="post" class="mt-3">
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="FirstMidName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="FirstMidName" class="form-control" placeholder="First Mid Name">
            </div>
            <span asp-validation-for="FirstMidName" class="text-danger"></span>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="LastName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="LastName" class="form-control" placeholder="Last Name">
            </div>
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="MajorID" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <select asp-for="MajorID" class="custom-select mr-sm-2"
                        asp-items="@ViewBag.MajorID"></select>
            </div>
            <span asp-validation-for="MajorID" class="text-danger"></span>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="EnrollmentDate" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="EnrollmentDate" class="form-control">
            </div>
            <span asp-validation-for="EnrollmentDate" class="text-danger"></span>
        </div>
        <div style="margin-top:10px" class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
        </div>
    </form>
</div>

Views/Learner/Edit.cshtml
@using UTC_LAB_4.Models;
@model Learner;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <div asp-validation-summary="All" class="text-danger"></div>
    <form asp-controller="Learner" asp-action="Edit" method="post" class="mt-3">
        <input type="hidden" name="LearnerID" value="@Model.LearnerID" />
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="FirstMidName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="FirstMidName" class="form-control" placeholder="First Mid Name" value="@Model.FirstMidName">
            </div>
            <span asp-validation-for="FirstMidName" class="text-danger"></span>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="LastName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="LastName" class="form-control" placeholder="Last Name" value="@Model.LastName">
            </div>
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="MajorID" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <select asp-for="MajorID" class="custom-select mr-sm-2"
                        asp-items="@ViewBag.MajorID"></select>
            </div>
            <span asp-validation-for="MajorID" class="text-danger"></span>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="EnrollmentDate" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="EnrollmentDate" class="form-control" value="@Model.EnrollmentDate">
            </div>
            <span asp-validation-for="EnrollmentDate" class="text-danger"></span>
        </div>
        <div style="margin-top:10px" class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Update</button>
            </div>
        </div>
    </form>
</div>

Views/Learner/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model IEnumerable<Learner>

<style>
    .btn-outline-primary[disabled] {
        color: white;
        background: rgb(100, 100, 250);
    }
</style>

<h1>Learner List</h1>
@await Component.InvokeAsync("Major")
<div id="table-container">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Mã</th>
                <th>Tên</th>
                <th>Họ</th>
                <th>Ngành</th>
                <th>Ngày Nhập Học</th>
                <th>Chức năng</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var s in Model)
            {
                <tr>
                    <td>@s.LearnerID</td>
                    <td>@s.FirstMidName</td>
                    <td>@s.LastName</td>
                    <td>@(@s.Major != null ? @s.Major.MajorName : "none")</td>
                    <td>@s.EnrollmentDate</td>
                    <td class="d-flex gap-1">
                        <a class="btn btn-outline-primary"
                           href="/Learner/Edit/@s.LearnerID">
                            <span class="material-symbols-outlined">
                                edit
                            </span>
                        </a>
                        <button class="btn btn-outline-primary"
                                onclick="HandleDelete(@s.LearnerID)"
                                type="button">
                            <span class="material-symbols-outlined">
                                delete
                            </span>
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="pagination d-flex justify-content-center">
        <ul class="list d-flex gap-1" style="list-style: none">
            <li>
                @if (ViewBag.HasPreviousPage)
                {
                    <button class="btn btn-outline-primary" onclick="HandlePagination(@(ViewBag.PageIndex - 1))">
                        Pre
                    </button>
                }
            </li>
            @for (int i = 1; i <= ViewBag.TotalPages; i++)
            {
                <li>
                    <button class="btn btn-outline-primary"
                    @(@i == ViewBag.PageIndex ? "disabled" : "")
                            onclick="HandlePagination(@i)">
                        @i
                    </button>
                </li>
            }
            <li>
                @if (ViewBag.HasNextPage)
                {
                    <button class="btn btn-outline-primary" onclick="HandlePagination(@(ViewBag.PageIndex + 1))">
                        Next
                    </button>
                }
            </li>
        </ul>
    </div>
</div>
<a asp-action="Create" class="btn btn-primary">Create New Student</a>

@section Scripts {
    <script>
        function HandleDelete(id) {
            console.log('handle delete');
            if (confirm("Are you sure to delete this learner?"))
                $.ajax({
                    type: "POST",
                    url: "/Learner/Delete",
                    data: {
                        LearnerID: id
                    },
                    error: function (err) {
                        console.log(JSON.parse(err.responseText))
                        if (JSON.parse(err.responseText).error)
                            alert("ERROR: " + JSON.parse(err.responseText).error);
                        else
                            alert("ERROR: " + JSON.stringify(err))
                    },
                    success: function (response) {
                        // Response
                        console.log(response);

                        if (response.error) {
                            alert("ERROR: " + response.error);
                        } else
                            window.location.href = '/Learner';
                    }
                });
        }

        function HandlePagination(page) {
            $.ajax({
                type: "GET",
                url: `/Learner/Page?pageIndex=${page}`,
                success: function (response) {
                    console.log(response);
                    document.querySelector('#table-container').innerHTML = response;
                }
            });
        }
    </script>
}

Views/Learner/IndexAJAX.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model IEnumerable<Learner>
<h1>Learner List</h1>
@await Component.InvokeAsync("MajorAjax")
<div id="content">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Mã</th>
                <th>Tên</th>
                <th>Họ</th>
                <th>Ngành</th>
                <th>Ngày Nhập Học</th>
                <th>Chức năng</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var s in Model)
            {
                <tr>
                    <td>@s.LearnerID</td>
                    <td>@s.FirstMidName</td>
                    <td>@s.LastName</td>
                    <td>@(@s.Major != null ? @s.Major.MajorName : "none")</td>
                    <td>@s.EnrollmentDate</td>
                    <td class="d-flex gap-1">
                        <a class="btn btn-outline-primary"
                           href="/Learner/Edit/@s.LearnerID">
                            <span class="material-symbols-outlined">
                                edit
                            </span>
                        </a>
                        <button class="btn btn-outline-primary"
                                onclick="HandleDelete(@s.LearnerID)"
                                type="button">
                            <span class="material-symbols-outlined">
                                delete
                            </span>
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<a asp-action="Create" class="btn btn-primary">Create New Student</a>


@section Scripts {
    <script>
        function HandleDelete(id) {
            console.log('handle delete');
            if (confirm("Are you sure to delete this learner?"))
                $.ajax({
                    type: "POST",
                    url: "/Learner/Delete",
                    data: {
                        LearnerID: id
                    },

                    success: function (response) {
                        // Response
                        console.log(response);

                        if (response.error) {
                            alert("ERROR: " + response.error);
                        } else
                            window.location.href = '/Learner';
                    }
                });
        }
    </script>

    <script>
        $(".major-list .major-list__item").on("click", function (e) {
            var id = $(this).attr("id");

            // Send a request to the server
            $.get({
                url: "/Learner/LearnByMajorID",
                data: { mid: id },
                error: function (err) {
                    alert(JSON.stringify(errr)) // Handling errors
                }
            }).done((response) => {
                $("div#content").html(response)
            })
        })
    </script>
}

Views/Learner/LearnerTable.cshtml
@model IEnumerable<Learner>
@if (Model.Count() > 0)
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Mã</th>
                <th>Tên</th>
                <th>Họ</th>
                <th>Ngành</th>
                <th>Ngày Nhập Học</th>
                <th>Chức năng</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var s in Model)
            {
                <tr>
                    <td>@s.LearnerID</td>
                    <td>@s.FirstMidName</td>
                    <td>@s.LastName</td>
                    <td>@(@s.Major != null ? @s.Major.MajorName : "none")</td>
                    <td>@s.EnrollmentDate</td>
                    <td class="d-flex gap-1">
                        <a class="btn btn-outline-primary"
                           href="/Learner/Edit/@s.LearnerID">
                            <span class="material-symbols-outlined">
                                edit
                            </span>
                        </a>
                        <button class="btn btn-outline-primary"
                                onclick="HandleDelete(@s.LearnerID)"
                                type="button">
                            <span class="material-symbols-outlined">
                                delete
                            </span>
                        </button>
                    </td>
                </tr>
            }
        </tbody>

    </table>
}
else
{
    <p>Chưa có người học nào.</p>
}

Views/Learner/Page.cshtml
@model IEnumerable<Learner>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Mã</th>
            <th>Tên</th>
            <th>Họ</th>
            <th>Ngành</th>
            <th>Ngày Nhập Học</th>
            <th>Chức năng</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var s in Model)
        {
            <tr>
                <td>@s.LearnerID</td>
                <td>@s.FirstMidName</td>
                <td>@s.LastName</td>
                <td>@(@s.Major != null ? @s.Major.MajorName : "none")</td>
                <td>@s.EnrollmentDate</td>
                <td class="d-flex gap-1">
                    <a class="btn btn-outline-primary"
                       href="/Learner/Edit/@s.LearnerID">
                        <span class="material-symbols-outlined">
                            edit
                        </span>
                    </a>
                    <button class="btn btn-outline-primary"
                            onclick="HandleDelete(@s.LearnerID)"
                            type="button">
                        <span class="material-symbols-outlined">
                            delete
                        </span>
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="pagination d-flex justify-content-center">
    <ul class="list d-flex gap-1" style="list-style: none">
        <li>
            @if (ViewBag.HasPreviousPage)
            {
                <button class="btn btn-outline-primary" onclick="HandlePagination(@(ViewBag.PageIndex - 1))">
                    Pre
                </button>
            }
        </li>
        @for (int i = 1; i <= ViewBag.TotalPages; i++)
        {
            <li>
                <button class="btn btn-outline-primary"
                @(@i == ViewBag.PageIndex ? "disabled" : "")
                        onclick="HandlePagination(@i)">
                    @i
                </button>
            </li>
        }
        <li>
            @if (ViewBag.HasNextPage)
            {
                <button class="btn btn-outline-primary" onclick="HandlePagination(@(ViewBag.PageIndex + 1))">
                    Next
                </button>
            }
        </li>
    </ul>
</div>